version: '3'

x-airflow-common: &airflow-common
  image: puckel/docker-airflow:1.10.9
  environment:
    - LOAD_EX=n
    - EXECUTOR=Local
    - FERNET_KEY=your_fernet_key_here
  volumes:
    - ./config:/usr/local/airflow/config
    - ./dags:/usr/local/airflow/dags
    - ./data:/usr/local/airflow/data
    - ./etls:/usr/local/airflow/etls
    - ./logs:/usr/local/airflow/logs
    - ./pipelines:/usr/local/airflow/pipelines
    - ./plugins:/usr/local/airflow/plugins
    - ./tests:/usr/local/airflow/tests
    - ./utils:/usr/local/airflow/utils
  ports:
    - "8080:8080"
  depends_on:
    - redis
    - postgres
  networks:
    - airflow

services:
  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    volumes:
    - ./config:/usr/local/airflow/config
    - ./dags:/usr/local/airflow/dags
    - ./data:/usr/local/airflow/data
    - ./etls:/usr/local/airflow/etls
    - ./logs:/usr/local/airflow/logs
    - ./pipelines:/usr/local/airflow/pipelines
    - ./plugins:/usr/local/airflow/plugins
    - ./tests:/usr/local/airflow/tests
    - ./utils:/usr/local/airflow/utils
    networks:
      - airflow

  scheduler:
    <<: *airflow-common
    command: scheduler
    networks:
      - airflow

  worker:
    <<: *airflow-common
    command: worker
    networks:
      - airflow

  flower:
    <<: *airflow-common
    command: flower
    ports:
      - "5555:5555"
    networks:
      - airflow

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - airflow

  redis:
    image: redis:latest
    networks:
      - airflow

networks:
  airflow:
    driver: bridge

volumes:
  postgres: